// Structured copy of docs/metrics.md, rendered by the in-app Metrics page.

export const RAW_OBSERVATION_COLUMNS = [
  ['input_tokens', 'Tokens sent to the model (prompt + context).'],
  ['output_tokens', 'Tokens generated by the model.'],
  ['total_tokens', 'input_tokens + output_tokens.'],
  ['cached_input_tokens', 'Input tokens served from a prompt cache (not re-prefilled).'],
  ['reasoning_tokens', '"Thinking" tokens on reasoning models (not visible output).'],
  ['total_cost', 'Cost in USD (Langfuse model-price calculation).'],
  ['input_cost / output_cost', 'Cost split by input / output.'],
  ['latency_ms', 'end_time − start_time.'],
  ['session_id', 'Groups multiple traces into one user/agent session.'],
  ['user_id · project_id · model · environment · trace_id', 'Attribution dimensions.'],
]

export const RAW_SCORE_COLUMNS = [
  ['trace_id / observation_id', 'What was scored.'],
  ['name', 'Eval name (e.g. correctness).'],
  ['value', 'Numeric score (typically 0–1).'],
  ['source', 'EVAL · ANNOTATION · API · …'],
]

export const MARTS = [
  {
    name: 'mrt_daily_usage',
    grain: 'day × project × team × user × model',
    note: 'The workhorse grain — every "by dimension" KPI rolls up from it.',
    fields: [
      ['observations', 'COUNT(*)'],
      ['traces', 'COUNT(DISTINCT trace_id)'],
      ['input / output / total tokens', 'SUM(...)'],
      ['cached_input_tokens / reasoning_tokens', 'SUM(...)'],
      ['total_cost', 'SUM(total_cost)'],
      ['team', 'joined from dim_user; "Unassigned" when unmapped'],
    ],
  },
  {
    name: 'mrt_model_efficiency',
    grain: 'per model',
    note: '',
    fields: [
      ['cache_hit_rate', 'SUM(cached_input_tokens) / SUM(input_tokens)'],
      ['reasoning_share', 'SUM(reasoning_tokens) / SUM(total_tokens)'],
      ['output_input_ratio', 'SUM(output_tokens) / SUM(input_tokens)'],
      ['cost_per_1k_tokens', 'SUM(total_cost) × 1000 / SUM(total_tokens)'],
      ['avg_latency_ms', 'AVG(latency_ms)'],
    ],
  },
  {
    name: 'mrt_session',
    grain: 'per session_id',
    note: 'The context-creep and cost-per-outcome signals.',
    fields: [
      ['turns', 'COUNT(DISTINCT trace_id) — model calls in the session'],
      ['observations', 'COUNT(*)'],
      ['input / output / total tokens', 'SUM(...)'],
      ['total_cost', 'SUM(total_cost)'],
      ['first_seen / last_seen', 'MIN / MAX(start_time)'],
    ],
  },
  {
    name: 'mrt_org_daily',
    grain: 'per day (whole org)',
    note: 'The cross-project org view Langfuse itself doesn’t provide.',
    fields: [['…', 'same fields as mrt_daily_usage, rolled up to day']],
  },
  {
    name: 'mrt_model_daily',
    grain: 'day × model',
    note: 'Leading indicators (cache hit, reasoning, cost/1k, out:in) as a time series.',
    fields: [
      ['cache_hit_rate', 'SUM(cached_input_tokens) / SUM(input_tokens)'],
      ['reasoning_share', 'SUM(reasoning_tokens) / SUM(total_tokens)'],
      ['output_input_ratio', 'SUM(output_tokens) / SUM(input_tokens)'],
      ['cost_per_1k_tokens', 'SUM(total_cost) × 1000 / SUM(total_tokens)'],
    ],
  },
  {
    name: 'mrt_hourly_usage',
    grain: 'hour × project',
    note: 'Intra-day cost/token grain for spike detection and heatmaps.',
    fields: [
      ['observations', 'COUNT(*)'],
      ['input / output / total tokens', 'SUM(...)'],
      ['total_cost', 'SUM(total_cost)'],
    ],
  },
  {
    name: 'mrt_governance_daily',
    grain: 'per day (latest canon snapshot)',
    note: 'Behaviour governance — proposals/ratifications over time.',
    fields: [
      ['ttrp_ms', 'time-to-first-ratified-policy (latest snapshot)'],
      ['precision14_ratio', 'ratified ≤ 14d ÷ decided within window'],
      ['proposals_total / pending / ratified / rejected / decayed', 'queue counts'],
    ],
  },
  {
    name: 'mrt_policy_coverage',
    grain: 'whole org (single row)',
    note: 'Share of traces covered by ratified policy evidence (upper bound — canon exports counts, not trace ids).',
    fields: [
      ['ratified_policies', 'COUNT(dim_policy)'],
      ['evidence_traces', 'SUM(evidence_traces)'],
      ['total_traces', 'COUNT(DISTINCT trace_id)'],
      ['coverage_ratio', 'evidence_traces ÷ total_traces'],
    ],
  },
]

export const METRIC_CATEGORIES = [
  {
    title: 'Cost',
    metrics: [
      { name: 'Cost (MTD)', endpoint: '/overview', formula: 'SUM(total_cost) since month start', why: 'The headline number; baseline for anomalies and budgets.' },
      { name: 'Cost trend', endpoint: '/daily', formula: 'daily SUM(total_cost) by dimension', why: 'Where spend is growing or shrinking.' },
      { name: 'Cost per 1k tokens', endpoint: '/overview', formula: 'SUM(total_cost) × 1000 / SUM(total_tokens)', why: 'Blended unit price; rises if you shift to pricier models or cache less.' },
      { name: 'Cost per active developer', endpoint: '/overview', formula: 'cost_mtd / COUNT(DISTINCT user_id)', why: 'The Uber "$/engineer" number — normalizes cost by adoption.' },
      { name: 'Cost per session', endpoint: '/overview · /sessions', formula: 'cost_mtd / COUNT(DISTINCT session_id)', why: 'Cost-per-outcome proxy — the "per-token is the wrong unit" fix.' },
      { name: 'Budget burn rate', endpoint: '/governance', formula: 'cost_mtd / monthly_budget', why: 'Forecast and alert before overspend.' },
      { name: 'WoW cost Δ', endpoint: '/overview', formula: '(last_7d − prior_7d) / prior_7d × 100', why: 'Week-over-week momentum.' },
      { name: 'Cost anomalies', endpoint: '/anomalies', formula: 'cost[day] > threshold × mean(prior 14 days)', why: 'Spike detection vs a rolling baseline — catch runaway spend early.' },
    ],
  },
  {
    title: 'Token efficiency',
    metrics: [
      { name: 'Output : Input ratio', endpoint: '/overview · /efficiency', formula: 'SUM(output_tokens) / SUM(input_tokens)', why: 'Context-bloat detector. A ratio collapsing toward 0 means you pay to re-read context with little output.' },
      { name: 'Context per session', endpoint: '/sessions', formula: 'SUM(input_tokens) per session', why: 'The #1 agent cost driver — context grows ~linearly each turn and is re-sent every turn.' },
      { name: 'Turns per session', endpoint: '/sessions', formula: 'COUNT(DISTINCT trace_id) per session', why: 'Agent-loop length; long loops × big context = cost explosion.' },
      { name: 'Input per turn', endpoint: '/sessions', formula: 'SUM(input_tokens) / SUM(turns)', why: 'Context growth rate — the steepness of the context-creep curve.' },
      { name: 'Cache hit rate', endpoint: '/overview · /efficiency', formula: 'SUM(cached_input_tokens) / SUM(input_tokens)', why: 'Prompt-caching savings; the single biggest immediate win for agentic workloads.' },
      { name: 'Reasoning share', endpoint: '/efficiency', formula: 'SUM(reasoning_tokens) / SUM(total_tokens)', why: 'Overhead of "thinking" models; flag where reasoning is disproportionate.' },
      { name: 'Tokens per task', endpoint: '/sessions', formula: 'total_tokens / turns', why: 'Unit token cost.' },
    ],
  },
  {
    title: 'Governance',
    metrics: [
      { name: 'Unattributed spend', endpoint: '/governance', formula: 'SUM(total_cost) WHERE team = \'Unassigned\'', why: 'Spend with no owner can’t be governed — surface it.' },
      { name: 'Spend concentration', endpoint: '/governance', formula: 'top-5 users’ cost ÷ total cost (30d)', why: 'Who to coach/optimize first; risk concentration.' },
      { name: 'Active users', endpoint: '/overview · /governance', formula: 'COUNT(DISTINCT user_id)', why: 'Adoption vs. cost sanity check.' },
      { name: 'Top spenders', endpoint: '/top', formula: 'SUM(total_cost) by dimension, ordered', why: 'Attribution for operator/developer conversations.' },
    ],
  },
  {
    title: 'Behaviour governance',
    metrics: [
      { name: 'Ratified policies', endpoint: '/behaviour', formula: 'COUNT(dim_policy)', why: 'The active canon — how much behaviour is pinned down as policy.' },
      { name: 'Time to first policy (TTRP)', endpoint: '/behaviour', formula: 'first governance.promote − first connect', why: 'Time-to-value for the governance loop.' },
      { name: 'Precision@14', endpoint: '/behaviour', formula: 'ratified ≤ 14d ÷ decided within window', why: 'Are proposals that get decided quickly ratified — signal quality of the queue.' },
      { name: 'Proposal queue', endpoint: '/behaviour', formula: 'total / pending / ratified / rejected / decayed', why: 'The human-ratification backlog.' },
      { name: 'Divergence by model × task', endpoint: '/behaviour', formula: 'divergent_traces ÷ total_traces per model × task-key', why: 'Where agents disagree on the same task — the raw material for policy.' },
    ],
  },
  {
    title: 'Quality',
    metrics: [
      { name: 'Avg latency', endpoint: '/efficiency', formula: 'AVG(latency_ms) per model', why: 'Routing decisions; cheap ≠ fast.' },
      { name: 'Pass rate', endpoint: '/quality', formula: 'passing ÷ scored, where MAX(value) ≥ threshold', why: 'Quality of what you’re paying for.' },
      { name: 'Cost per successful outcome', endpoint: '/quality', formula: 'Σ cost(passing traces) ÷ count(passing)', why: 'The metric Uber lacked — cost tied to passing work.' },
      { name: 'Cost per scored trace', endpoint: '/quality', formula: 'Σ cost(scored traces) ÷ count(scored)', why: 'Baseline cost per evaluable unit of work.' },
    ],
  },
  {
    title: 'Time series & forecasting',
    metrics: [
      { name: 'Budget burn-down', endpoint: '/burndown', formula: 'cumulative cost vs budget; projected = cumulative + avg_daily × days_remaining', why: 'Will we blow the budget by month-end?' },
      { name: 'Efficiency trend', endpoint: '/model-daily', formula: 'cache-hit / reasoning / cost-per-1k / out:in per day', why: 'Leading indicators — they move before cost does.' },
      { name: 'Hourly usage', endpoint: '/hourly', formula: 'SUM(total_cost) by hour of day', why: 'Intra-day spikes; when agents run.' },
      { name: 'Baseline & z-score', endpoint: '/baseline', formula: 'trailing-14d mean/std + day-of-week baseline', why: 'Seasonality-aware anomaly detection (fewer false positives).' },
      { name: 'Period over period', endpoint: '/periods', formula: 'weekly/monthly totals with WoW/MoM %', why: 'Finance-standard rollups.' },
      { name: 'Trend & change points', endpoint: '/trend', formula: 'rolling 7-day slope + sign flips', why: 'Detect regime shifts (model upgrade, prompt change).' },
      { name: 'Cohorts', endpoint: '/cohort', formula: 'cost by first-week cohort × week-since-adoption', why: 'New-developer ramp and retention.' },
    ],
  },
]
